// AUTO-GENERATED from the vault locked copy. Do not edit by hand.
// Regenerate with: node scripts/gen-wiring.mjs
// Sources: MPowered_Reset_Patterns_FINAL.md (write-ups + Suggestions),
//          MPowered_Reset_Stage2_Action_Rewrites.md (action-rewrites).

export interface WiringContent {
  archetype: string;
  title: string;
  tagline: string;
  body: string;
  suggestions: string;
  actionRewrite: string;
}

export const WIRING_CONTENT: Record<string, WiringContent> = {
  "Steady Engine": {
    "archetype": "Steady Engine",
    "title": "The Steady Engine",
    "tagline": "Your energy is strongest when you care about what you're doing.",
    "body": "When the work matters to you, you have real staying power. You can settle in and keep going at a steady pace, without big highs or hard crashes. This is a quiet strength. You are the one who can stay with something, see it through, and not burn out, as long as you care about the work.\n\nBut your energy has a condition. It runs on finding it interesting. When the work means something to you, your tank stays full. When it doesn't, the same task can drain you far faster than it does others, even if it's easy. This is why a boring job can leave you more tired than a hard one. You are running an engine that needs the fuel it isn't getting.\n\nThis matters more in perimenopause and menopause. Estrogen and progesterone help keep your energy steady and your sleep deep, and both are shifting. This can mean your baseline reserve may run lower than it did. So there's less to spare for work that doesn't interest you, and the draining tasks cost you more, sooner.\n\nWhen you are able to operate at your best, you protect your steady energy by spending most of it on what holds your interest, and handling the dull-but-necessary tasks in small, contained doses. When you do, you stop ending every day scraped empty, and there's more of you left for your own life.",
    "suggestions": "Look at where your energy goes each day. How much of it is spent on work that means something to you, and how much disappears into tasks that don't? You don't need to love everything. But notice the difference between a tiring day spent on work that matters and a draining day spent on work that doesn't. Where you can, group the dull tasks together and cap the time you give them, so they don't drain the energy you need for the work that fills you back up.",
    "actionRewrite": "You work best at a steady, even pace, but dull tasks can be a big energy drain for you. If you can pull those draining tasks into one contained block instead of letting them scatter across your whole day, you should find you feel less worn down by evening, because the drain isn't following you from morning to night. A couple of things to try:\n- For three days, if you can, group your draining tasks into one time block and put a hard stop on how long you spend on them, rather than spreading them through the day.\n- Notice which tasks leave you most drained, and keep them out of your best hours where you have any say over your schedule."
  },
  "Wave Worker": {
    "archetype": "Wave Worker",
    "title": "The Wave Worker",
    "tagline": "Your energy comes in waves, not a straight line.",
    "body": "When you're in a high, you can do a lot, fast. You get more done in one strong stretch than most people do all day. This is a real gift. You're built for the burst, for the focused push where everything clicks and the work pours out of you.\n\nBut a wave that rises has to come down. After your high, you need a real rest before the next one. This is how your energy is built. The trouble starts if you treat your low like a problem to push through, instead of the recovery your next wave depends on. If you spend the dip fighting yourself, then the next high won't come, because you never let the trough do its job.\n\nThat rhythm is harder to honour in perimenopause and menopause. The hormones that used to top up your energy and steady your sleep are changing, your lows may feel lower and your recovery can take longer than it did. The push-through mentality you used to get away with will now cost you the whole next day.\n\nAt your best, you ride your highs and rest during your lows on purpose, and you even build the dip into your task management, so the wave can rise again. When you stop fighting the trough, the hard crashes soften, and you get more out of your good stretches with less wreckage after them.",
    "suggestions": "Start noticing your own rhythm. When in the day does your strong stretch usually come, and when does the dip arrive? Most wave workers have a pattern they've never mapped. Daily, weekly, and task based. Once you see it, if you can, put your hardest, most important work inside your high, and let the low be lighter on purpose. The rest is what buys you your next good stretch. Fighting the trough is what flattens the wave for good.",
    "actionRewrite": "You get a lot done in strong bursts, then need real recovery before the next one. When you stop fighting your dips and start working with your rhythm, you get more out of your good stretches and crash less at the end of the day. A couple of things to try:\n- This week, notice what time your strong stretch usually comes, and move your hardest task into it if you can.\n- When your energy dips, switch to something lighter for that stretch instead of pushing through. The dip is how your next burst recharges."
  },
  "Outside-In Worker": {
    "archetype": "Outside-In Worker",
    "title": "The Outside-In Worker",
    "tagline": "Your energy comes from what's around you.",
    "body": "For you, the room matters. The people matter. When you're in the right space, with the right people, you light up and the work feels easier. When you're in the wrong one, you can drain fast, no matter how much you care about the task itself. This is real. Your energy is wired to respond to your surroundings.\n\nThis is a strength when you know it. You can walk into a good space and feel the work get lighter. The shadow shows up when you ignore it, when you try to push through a draining space and can't understand why you feel so flat, when the real problem is the room.\n\nYour surroundings matter even more in perimenopause and menopause. As estrogen and progesterone shift, your system can be more sensitive to stress, noise, and the moods around you, so a draining environment costs you more than it did, and a good one helps you more.\n\nAt your best, you stop trying to power through bad spaces and start choosing better ones. When you do, the work stops feeling like wading through mud, and you keep more of your energy for what matters.",
    "suggestions": "Pay attention to where and with whom you work best. Is there a spot, a time, or a person that makes the work feel lighter? Many outside-in workers have never named this, so they keep trying to push through in places that drain them. Where you can, move your harder work into the settings that lift you, even small changes like a different room, working near a steady friend, or stepping away from a draining space. You're working with how you're built.",
    "actionRewrite": "Your energy rises and falls with where you are and who you're around, so the right setting can do half the work for you. When you stop forcing yourself to push through draining spaces, you'll likely feel steadier and less wiped out by the end of the day. A couple of things to try:\n- This week, notice one setting that leaves you more drained and one that leaves you steadier, and spend a little more of your work time in the better one where you can.\n- Before a hard task, change your spot if you're able: a different room, a window, away from a draining person."
  },
  "Responder": {
    "archetype": "Responder",
    "title": "The Responder",
    "tagline": "You start fast when the work is already defined. You stall when you have to invent it.",
    "body": "Hand you a real task, here's the project, here's what's needed, here's the problem, and you're off. You don't need a pep talk or a warm-up. The work has edges, so you grab it and go. This is a genuine strength, and the people around you rely on it, even if they've never said so.\n\nThe blank page is a different story. When you have to decide what the work even \\*is\\* before you can touch it, you stall. You might reread the same email. You may answer three easy things to avoid the hard one. You may get a sudden urge to tidy your desk. You are someone who works \\*on\\* things, and right now there's no thing yet, just empty space you're meant to fill out of nowhere.\n\nHere's the tell: a boring task someone handed you is often easier to start than an exciting one you have to dream up yourself. So it's less about how interesting the work is, and more about whether someone already gave it a shape.\n\nThe cold start also takes more out of you now. When you push to begin from nothing, your body reads that pressure as stress. And because the hormones that used to buffer that stress are lower now, cortisol (your stress hormone) can climb faster and higher. So the blank page doesn't just feel hard, it can wind you up. You might feel it as a foggy stall, a restless itch, or a short fuse before you've taken a single action.\n\nAt your best, you stop trying to summon work from an empty page. You get something real in front of you first, and you run with it. The starts stop feeling like dread, and that wound-up, behind-before-you-begin feeling eases off your mornings.",
    "suggestions": "Notice where your day makes you start from nothing. Those are some of your most expensive moments, and they're often where you stall out. You can't always pick your tasks, but you can almost always pick how you begin. Pull up the old version. Reread the request out loud. Write one bad first sentence you fully intend to delete. Ask someone a quick question. Anything that puts a real thing in front of you. And when nothing’s been handed to you, build the structure yourself first. That’s your version of a real start. If you work with others, ask a few questions up front to turn a vague ask into a clear brief. If you’re on your own, make the shape before you make the thing: a quick checklist, a rough outline, three concrete steps. You're handing yourself something to work on, and the moment the work has edges, you're moving.",
    "actionRewrite": "You start fast when work is already shaped, and stall at a blank page, so the trick is to never start from nothing. Once there's something concrete in front of you, you move quickly and the dread lifts. A couple of things to try:\n- Before any blank-page task this week, give yourself something to react to first: reopen the last version, reread the request out loud, or write one rough line you plan to delete.\n- If you can, don't save your \"start from scratch\" tasks for late in the day when you're already empty. Begin them when there's something to push against."
  },
  "Initiator": {
    "archetype": "Initiator",
    "title": "The Initiator",
    "tagline": "You start best from your own ideas. Pure reacting all day wears you down.",
    "body": "An idea hits and you want to move on it. You'd rather build your own thing than sit and answer what other people hand you. You're the one who sees what could be better and starts on it while everyone else is still talking about it. That's a real gift, and it's probably gotten you further than you give it credit for.\n\nHere's where it costs you. When your whole day is other people's requests, reply to this, fix that, handle the next thing, you may go flat. Not tired exactly. Restless. Busy from morning to night, but with nothing of your own to show for it. You might catch yourself thinking, I did so much today, so why does it feel like I did nothing? That feeling is a builder with nothing of her own to build.\n\nThis weighs more now, too. That low, all-day friction keeps your nervous system switched on, and because the hormones that used to take the edge off are lower now, particularly progesterone, that tension can sit in you longer than it did. You might feel it as an edge you can't shake, trouble settling at night, or a wired-but-drained feeling even after a day where everything technically got done.\n\nAt your best, you guard a little room for something of your own, so the reacting doesn't swallow the whole day. The restless, did-nothing feeling lifts, and you end more days with something that felt like yours.",
    "suggestions": "Look at how much of your day is pure reaction versus something you started. If it's all reaction, that's your drain, even when every single task is reasonable. You may not control your workload, but most people can find a small corner: a side idea, a better way to do a thing, one question worth chasing. Even fifteen minutes of your own creation changes how the reactive hours feel. You're built to start things. Give that part of you somewhere to go, even somewhere small.",
    "actionRewrite": "You work best starting your own ideas, and go flat in a day that's all reacting to others. Even a small piece of your own work changes how the whole day feels, so you end it less restless and more satisfied. A couple of things to try:\n- This week, protect even fifteen minutes for something of your own: a side idea, a better way to do a task, or a question worth chasing.\n- If your whole day is answering other people, notice that this is the drain, even when each task is fine on its own. Even simple acknowledgement can lift some of the burden."
  },
  "Collaborator": {
    "archetype": "Collaborator",
    "title": "The Collaborator",
    "tagline": "You start best with other people. A blank page alone is where you stall.",
    "body": "Put you in a room with a couple of other people and a thing to figure out, and you're at your best. Ideas come easily when there's someone to bounce off. You build on what they say, they build on what you say, and the work takes shape between you. You're not waiting to be handed a finished plan, and you're not trying to pull it out of thin air by yourself. You think best \\*out loud, with company.\\*\n\nThe hard part is starting alone. Sit you in front of a blank document with the door shut and the same brain that sparks in a group can go quiet. You read the brief again. You open a new tab. You wait for an idea that won't come, because the thing that starts your engine isn't there: another person.\n\nHere's how you know: if you can talk an idea through with someone, it flows and clicks into place. If you sit down to write up that same idea alone, you may feel completely stuck on the very thing you just talked through. The idea was never the problem. The aloneness was.\n\nStarting cold and alone also takes more out of you now. When you push to begin from a blank page with no one to spark off, your body reads that pressure as stress. And with less of the hormonal buffer you used to have, cortisol (your stress hormone) can climb faster and higher than before. So the empty room doesn't just feel slow, it can wind you up. You might notice it as a foggy stall, a restless can't-settle feeling, frustration or anger, or an anxious feeling before you've even begun.\n\nAt your best, you stop forcing the solo cold start. You get a person into the room first, even briefly, and let the work catch fire the way it does for you: together. The tasks you used to dread alone start moving again, and the day stops costing you so much before it's even begun.",
    "suggestions": "Notice which tasks you keep putting off, and check whether they're the ones you're facing alone. That's often the real pattern, not the task itself. You can't always work in a group, but you may be able to borrow a person for the \\*start.\\* Talk the idea through with someone before you sit down to do it solo. Send a colleague a quick \"here's what I'm thinking, does this track?\" Ask one person to be your sounding board for a few minutes. You don't need them for the whole job. You need them to help you light the first spark. Once the thing is moving, you can often carry it alone from there.",
    "actionRewrite": "You start best with another person, and stall alone at a blank page, so the fix is to borrow someone for the start, not the whole job. With a person to spark off, the task you've been avoiding often gets moving in minutes. A couple of things to try:\n- Before a task you keep putting off, check if it's one you're facing alone. If so, talk it through with someone for a few minutes before you sit down to do it solo.\n- When you can't get a person in the room, send a quick \"here's what I'm thinking, does this track?\" to a colleague to get yourself started."
  },
  "Sleeper": {
    "archetype": "Sleeper",
    "title": "The Sleeper",
    "tagline": "You decide best when you give it time. Forcing a fast answer is where you go wrong.",
    "body": "Your clarity arrives slowly. Sleep on a decision and you often wake up knowing, sometimes the next day, sometimes a few days on. The right answer tends to rise on its own once you stop forcing it. This is real wisdom, and the choices you let settle tend to be the ones you don't regret.\n\nThe trouble comes when you're pushed to decide on the spot. Cornered for an answer right now, you might freeze, or commit to something that feels wrong by the next morning. You may know the feeling of saying yes in a meeting and lying awake that night, realizing it wasn't right. That is a good decision-maker forced to work in a way she isn't built for.\n\nIt's worse when your emotions are fluctuating. Decide on a high and you can overcommit. Decide on a low and you might shut something down you'll later wish you'd kept. For your truth to emerge, it needs the wave to pass first.\n\nThe rushed decision carries a higher price now, too. Because estrogen helps keep your thinking sharp, and it's dropping, your working memory, the part of your mind that holds several things at once, has less room. So being asked to weigh everything on the spot can flood a brain that's already running closer to full. The forced quick answer doesn't just feel hard, it can scramble, and you may notice your brain going blank, or second-guessing a choice you can't quite think straight about.\n\nAt your best, you stop letting other people's urgency set your timing. You give the choice the time you need, and you decide from calm. When you do, the second-guessing settles, and the mental spinning that drains your afternoons goes with it. You get back the bandwidth it was eating, and the day feels lighter for it.",
    "suggestions": "Notice how often you're pushed to decide faster than feels right, and how those decisions tend to turn out. Most sleepers can buy more time than they think. \"Let me get back to you this afternoon\" is almost always available, even when it feels like it isn't. For any decision that can wait, give yourself the night, or longer if you need it. Check in the next day: does it still feel right? If no, give yourself more time where you can. If yes, move. You're using the one thing your decisions need, which is time.",
    "actionRewrite": "Your best decisions come with time, not on the spot, so the win is giving yourself the gap you need. When you stop forcing answers while you're drained, you make fewer choices you regret and lose less sleep over them. A couple of things to try:\n- For three days, on any decision that can wait, give yourself until the next day. \"Let me come back to you tomorrow\" is almost always available.\n- When you feel pushed to decide right now and you're drained, treat that pressure as a sign to wait, not to rush."
  },
  "Gut-Knower": {
    "archetype": "Gut-Knower",
    "title": "The Gut-Knower",
    "tagline": "Your first instinct is usually right. Overthinking it is where you tie yourself in knots.",
    "body": "You know fast. The answer lands in your body almost before the question's finished. A clear yes, or a clear no. This is a real gift. Your gut is quick and it's usually right, and the people who decide alongside you often wish they had your speed.\n\nThe damage comes after, when you start to argue with it. You get the clean instinct, then you can talk yourself out of it. Maybe you make a list of pros and cons for a thing you already knew the answer to. Maybe you ask five people and end up more confused than when you started. By the time you've \"thought it through,\" you've buried the right answer under an hour of doubt and you can't find it again.\n\nHere's the giveaway: your worst decisions usually aren't your first instinct. They're the ones where you overrode it. The gut was right. The overthinking is what got you.\n\nThat second-guessing has a steeper cost now. Because the prefrontal cortex, the part of your brain that runs all that analysis is stimulated by estrogen, and there's less of it now, it tires faster and gets overwhelmed sooner. So the more rational deliberation you pile on top of a clear gut call, the more scrambled it can get. You may notice it as spinning, decision fatigue, over thinking, or a simple choice suddenly feeling far more complicated than it is.\n\nAt your best, you trust the fast read and act on it before the doubt floods in. The hours you used to lose to spinning come back to you, and the decision fatigue that flattened your afternoons lifts. You move through the day with a clearer head and more left in the tank.",
    "suggestions": "Start catching your first instinct before the second-guessing starts. On small decisions especially, name the gut answer out loud or jot it down the moment it lands, then notice how often it was right and you talked yourself out of it. For the everyday choices, trust the first hit and move. Save the heavy deliberation for the rare decision that earns it.",
    "actionRewrite": "Your first instinct is usually right, and overthinking is what ties you in knots, so trusting the fast answer saves you. You'll spend less of your day spinning and feel clearer for it. A couple of things to try:\n- This week, on small decisions, jot down your first gut answer the moment it lands, then notice how often it was right and you talked yourself out of it, or how much it cost in over analyzing.\n- Save your heavy back-and-forth for the few big decisions that earn it. For everyday ones, go with the first clear answer and move on."
  },
  "Talker": {
    "archetype": "Talker",
    "title": "The Talker",
    "tagline": "You decide best out loud. Trying to sort it silently in your head is slow and draining.",
    "body": "You often don't fully know what you're thinking until you say it out loud. Talk a decision through with one person and it can untangle in minutes. The answer was in you the whole time, it just needed a voice and a listener to come out. This is real. Saying it aloud is how you find your clarity, the same way other people find theirs in silence.\n\nThe trouble is when you try to decide alone in your head. Here's what can happen: the thought goes round and round, the same loop, no exit. You might spend a whole day circling a choice that one short conversation would have settled. The circling is just you cut off from the way you reach an answer, which is out loud.\n\nHow many times have you been mid-sentence explaining a problem to someone and stopped, because you suddenly knew the answer? You didn't need their advice. You needed to hear yourself think.\n\nThe silent loop drains you more now than it once did. Because estrogen helps your working memory hold things steady, and there's less of it to draw on, your mind has less room to work a problem through, so it just loops. You may notice it as rumination that won't quit, lying awake running the same decision, or a foggy stuck feeling that lifts the moment you finally talk it out.\n\nAt your best, you stop forcing the lonely deliberation. You take the decision out of your head and into a conversation, where it sorts itself. The all-day rumination that wears you down eases, and you stop carrying unmade decisions into your evening. You end the day with a quieter mind.",
    "suggestions": "Notice the decisions you keep circling alone. That circling is the drain, not the decision. You don't need a formal meeting or expert advice. You need a sounding board, someone to think out loud at for a few minutes. A colleague, a friend, even a voice note to yourself can work. Get the words out of the loop and into the air. Hearing yourself say it is how you find your own answer.",
    "actionRewrite": "You reach clarity out loud, not silently in your head, so the loops you spin alone are the slow, draining way for you. One short conversation often untangles what a whole day of circling can't. A couple of things to try:\n- When you catch yourself circling a decision alone, say it out loud to someone for a few minutes, or record yourself talking it through.\n- Notice which choices you've been stuck on in your head for days. Those are the ones to take into a conversation this week."
  },
  "Frustration": {
    "archetype": "Frustration",
    "title": "The Frustration Signal",
    "tagline": "When something doesn't suit you, you feel stuck. Pushing harder and getting nowhere.",
    "body": "When something's out of alignment for you, when the work doesn't suit your strengths or how you work best, your early warning is frustration. You might feel it as effort that won't land. You're pushing and pushing, working harder, and the thing just won't move. That stuck, grinding feeling is your signal. It's often the first sign that something is off, showing up before you've consciously worked out what.\n\nMost of us were taught to override frustration. Push through it, try harder, don't complain. But for you, powering through is the trap, because the frustration was the message, and overriding it just means spending more and more energy forcing something that was never going to move the way you're attacking it.\n\nHere's what's worth knowing about why it builds. Frustration is a low-grade threat signal, and because falling estrogen and progesterone leave your nervous system with less of the buffer they used to give it, it can read threat faster and hold onto it longer than it did. So the frustration you could once shake off may now sit in you, climb through the day, and tip into something heavier if you ignore it.\n\nWhen you learn to read it, frustration becomes useful. It's telling you to stop pushing this way and find another angle, or step back entirely. And when you read it early, you stop burning yourself out forcing what won't move, and you get that energy back for the work that fits you.",
    "suggestions": "Start treating frustration as information. When you notice it building, that grinding \"why won't this move\" feeling, pause before you push harder. Ask one question: is this stuck because I need a different approach, or because this isn't right for me at all? You can't always walk away from the thing causing it, especially at work. But even naming it, this is my frustration signal, something here is off, is enough to stop you burning another hour forcing it.",
    "actionRewrite": "When something doesn't suit you, you feel stuck and pushing, and that frustration is useful information once you stop overriding it. Reading it early saves you from burning energy forcing something that was never going to move that way. A couple of things to try:\n- This week, when that grinding \"why won't this move\" feeling shows up, pause before you push harder and ask: do I need a different approach here, or is this just not right for me?\n- Where you can't change the task, even naming \"this is my frustration signal\" tells you to stop forcing and look for another angle."
  },
  "Resentment": {
    "archetype": "Resentment",
    "title": "The Resentment Signal",
    "tagline": "When something doesn't suit you, you feel it as resentment. Working hard for too little, and not being seen.",
    "body": "When something's out of alignment for you, when the work doesn't suit your strengths or how you work best, your early warning is resentment. It builds as a slow \"this isn't fair.\" Maybe you're working harder than anyone and it's going unrecognized. Maybe you're giving far more than you're getting back. Maybe you're carrying the load while someone else gets the credit. However it shows up, the common thread is the same: you're putting in more than is coming back to you, and bitterness can start to creep in. That feeling is your signal that the balance here has tipped, and you've been running at a loss.\n\nMost of us are taught to swallow resentment. Be gracious, don't make it about you, keep going. But for you, swallowing it is the trap, because the resentment was the message, and ignoring it just means you keep pouring yourself into something that isn't paying you back, in recognition, in reward, or in basic fairness.\n\nHere's why it lands harder now. Resentment keeps your nervous system in a low simmer of threat, and because the hormones that used to settle it are lower now, that simmer can be quicker to start and slower to cool. So the unfairness that once stayed background may now hum louder, wear on you, and curdle into something that affects how you feel about your work and the people in it.\n\nWhen you learn to read it, resentment becomes useful. It's telling you the exchange here is off, and something needs to change before you've given past empty. And when you catch it early, you can rebalance before the bitterness takes root, and you stop carrying that low simmer home with you.",
    "suggestions": "Start treating resentment as data. When you catch that \"I'm doing so much for so little\" feeling, take it seriously rather than pushing it down. Ask: where am I putting in more than I'm getting back, and is there any way to rebalance it, ask for what I'm owed, or give a little less here? You can't always fix every unfair setup, especially at work. But even seeing it, this is my resentment signal, the exchange has tipped against me, tells you where to look first.",
    "actionRewrite": "When something doesn't suit you, you feel you're giving more than you're getting back, and that resentment is data worth reading. Catching it early means you can rebalance before you've given past empty. A couple of things to try:\n- When you notice the \"I do so much and it's not seen\" feeling, look at where you're putting in more than you're getting back, instead of pushing the feeling down.\n- This week, pick one place that's tipped against you and see if you can ask for what you're owed, or give a little less, where it's safe to."
  },
  "Flatness": {
    "archetype": "Flatness",
    "title": "The Flatness Signal",
    "tagline": "When something doesn't suit you, you go flat. No spark, more tired than the task warrants.",
    "body": "When something's out of alignment for you, when the work doesn't suit your strengths or how you work best, your early warning is flatness. You may feel it as a draining of colour and energy. Not angry, not resentful, just done. The spark is gone, you're going through the motions, and you may be far more tired than the task itself can explain. That flatness is your signal that something here has stopped being right for you.\n\nMost of us are taught to push past flatness. Caffeine, willpower, just get it done. But for you, pushing past it is the trap, because the flatness was the message, and overriding it just empties you further while you ignore the thing it was pointing at.\n\nHere's the part worth knowing. The mismatch between how tired you feel and how demanding the work is, that gap is the tell, and it's real. Your nervous system registers \"this doesn't suit me\" as a drop in energy and drive, and because shifting hormones leave it more sensitive, that signal can read louder against an already lower baseline. So the flatness that used to be easy to shrug off can now feel like hitting a wall.\n\nWhen you learn to read it, flatness becomes useful. It's telling you that something here has gone misaligned, and it's worth listening before you run yourself all the way down. When you catch it early, you stop pouring yourself into what was never right for you, and that bone-deep tiredness the work didn't earn starts to lift.",
    "suggestions": "Start treating flatness as a signal. When the tiredness doesn't match the task, that \"why am I this drained by something this small\" feeling, notice it rather than caffeinating over it. Ask: what specifically am I flat about here, and is any part of it something I can shift or step back from? You can't always change the work itself. But even recognizing it, this is my flatness signal, something here has gone off, points you at the real thing.",
    "actionRewrite": "When something doesn't suit you, you go flat and more tired than the task should make you, and that gap is the signal worth reading. Listening to it early stops you from emptying the tank before you notice anything's wrong. A couple of things to try:\n- When your tiredness doesn't match how hard the task is, treat it as a signal before you reach for caffeine.\n- Ask what specifically you've gone flat about, and whether any small part of it can shift or come off your plate, where you have a say."
  },
  "Deep Diver": {
    "archetype": "Deep Diver",
    "title": "The Deep Diver",
    "tagline": "Your focus works in deep, uninterrupted blocks. Fractured time is where it falls apart.",
    "body": "You do your real thinking when the world goes quiet and you can drop all the way in. Give you a true block of uninterrupted time, no pings, no one needing you, and you go deep, and the good work comes out. This is a real strength. You're capable of a depth of focus that scattered, busy people never reach.\n\nThe trouble is that you can't do that work in the gaps. Fifteen minutes between meetings, a half hour with one ear open for interruptions, the afternoon chopped into pieces, none of it works for you. You need time to descend, and every interruption sends you back to the surface to start the dive again. From the outside it can look like you're slow to get going. What's happening is you keep getting handed shallow time for work that needs depth.\n\nHere's how you know: you can lose a whole fractured day to a task that would have taken ninety quiet minutes, and end it exhausted with almost nothing to show, because you kept getting pulled back up before you reached the bottom.\n\nThat constant surfacing takes a bigger toll in perimenopause and menopause. Because estrogen helps your brain switch and refocus smoothly, and it's dropping, moving your attention back and forth gets harder, and every interruption forces a fresh, effortful re-entry into the work. Each switch has a cost, and your brain may pay it slower now. You may notice it as losing your thread when you're pulled away, taking ages to get back into something after a break, or a foggy \"where was I\" that didn't used to happen.\n\nAt your best, you stop trying to do deep work in shallow time. You protect real blocks, even small ones, and guard them like they matter. When you get even one, the work that used to eat a whole scattered day gets done in a fraction of it, and you come out the other side far less fried.",
    "suggestions": "Notice which tasks need depth and which don't, and stop trying to do the deep ones in the cracks. You can't always control your calendar, but most people can protect more than they think: one uninterrupted block, a closed door, notifications off for forty minutes, an early start before the pings begin. Even one real block beats a whole day of fragments. And protect the descent, the first ten minutes where nothing seems to be happening are you getting to the depth where the work lives.",
    "actionRewrite": "Your real thinking needs deep, uninterrupted time, not the gaps between things, so protecting one real block beats a whole day of fragments. You'll get more done in forty quiet minutes than in a chopped-up afternoon, and feel far less foggy. A couple of things to try:\n- This week, protect one block of at least forty minutes for your hardest thinking: door closed, notifications off, if you can manage it.\n- Stop trying to do your deepest work in ten-minute gaps between meetings. Move it to your most protected stretch instead."
  },
  "Open-Door Thinker": {
    "archetype": "Open-Door Thinker",
    "title": "The Open-Door Thinker",
    "tagline": "Your focus works better with life around you. Total isolation is where you stall.",
    "body": "You think best when there's some life around you. A bit of background hum, people nearby, a sense of not being sealed off. The world being present helps you stay present. This is real. Some minds settle in stimulation, and yours is one of them.\n\nThe trouble is total isolation. Shut you alone in a silent room to focus and your mind can get loud and restless instead of calm. You might start checking your phone, getting up, looking for any sign of life. An empty, silent room is simply the one setting your focus can't work in.\n\nHere's the giveaway: you probably get more done at a café, or with someone working nearby, than you ever do alone at your desk with the door shut, and you may have felt guilty about that, as though real focus is supposed to happen in silence. For you, it doesn't.\n\nForced isolation is harder in perimenopause and menopause. Because the hormones that used to help your mind settle are fluctuating, a restless, under-stimulated mind can be harder to quiet, and forcing focus in a dead-quiet room burns energy you can't spare. You may notice it as fidgeting, rereading, or a wired restlessness that lifts the moment you're somewhere with a little life in it.\n\nAt your best, you stop forcing focus in silence and put yourself where there's gentle life around you. The restlessness eases, the work flows instead of grinding, and you stop ending focus sessions more frazzled than when you began.",
    "suggestions": "Notice where you get your best work done, and take it seriously even if it looks unproductive. You can't always pick your environment, but you can often add a little life: work from a café, a co-working space, or a shared table. Put on low background noise. Sit near a steady colleague. You don't need conversation, just the hum of others around you. A table near a little life will often do what an hour of forcing silence can't.",
    "actionRewrite": "You focus better with a little life around you than in total silence, so the empty, sealed-off room is working against you. Put yourself somewhere with gentle background life and the restlessness eases. A couple of things to try:\n- This week, try a focus task somewhere with gentle background life: a café, a shared table, near a quiet colleague, or with low background noise on.\n- Stop forcing yourself to concentrate in dead silence when a little life around you works better."
  },
  "Mover": {
    "archetype": "Mover",
    "title": "The Mover",
    "tagline": "Your focus works when your body moves. Sitting still too long is where it fades.",
    "body": "Your mind works best when your body isn't pinned in place. A walk, a change of room, standing up, moving, that's when your thinking clears and the ideas come. This is real. For you, motion and focus are connected, and stillness is not the neutral state it's sold as.\n\nThe trouble is being made to sit still for hours. Pinned to a chair through a long stretch, your focus doesn't sharpen, it drains away. You can get foggy, antsy, and slow, and the harder you force yourself to stay put and concentrate, the worse it gets. The restlessness is the signal: your focus runs on movement, and it has been sitting still too long.\n\nHow many times has the answer arrived on a walk, in the shower, the moment you got up from the desk, the exact thing you couldn't reach while sitting and staring at it? That's not a coincidence. That's how your mind works.\n\nBeing made to sit still wears on you faster in perimenopause and menopause. Because shifting hormones can leave your thinking foggier and slower to clear, a stuck mind is more common now, and the movement that clears it is one of the most reliable ways you have to get your focus back. You may notice it as a heavy mental fog while seated that lifts as soon as you stand, walk, or change your surroundings.\n\nAt your best, you use movement as the tool it is for you, to clear the fog and reach the thought. When you do, the fog clears faster, the answers come quicker, and the work stops feeling like pushing a boulder uphill.",
    "suggestions": "Notice when your thinking goes foggy, and check whether you've been sitting too long. Movement is often the fix, not more willpower. You can't always get up, but most people can build in more motion than they do: take the call walking, think through a problem on a short walk, stand up, change rooms, step outside between tasks. When you hit a wall, stop staring and move. The answer often arrives the moment you do.",
    "actionRewrite": "Your thinking clears when your body moves and fogs when you sit too long, so movement is one of your sharpest thinking tools. The answer you can't reach at the desk often arrives the moment you get up. A couple of things to try:\n- When your thinking goes foggy, check how long you've been sitting. If you can, stand, change rooms, or take a short walk before trying again.\n- This week, take one call walking, or think through one stuck problem on a five-minute walk instead of staring at the screen."
  },
  "Wave Rider": {
    "archetype": "Wave Rider",
    "title": "The Wave Rider",
    "tagline": "Your emotions move in waves. Acting at the peak is where you get into trouble.",
    "body": "Your feelings come in waves, and they move through you with real intensity. When something hits, you feel it fully, the high is high and the low is low. This is how you're built, and when you understand it, it's a kind of emotional honesty most people never reach.\n\nThe trouble comes when you act at the top or bottom of a wave. You might fire off the email while you're angry, make the promise while you're elated, or quit the thing while you're low, and then wake up the next day in a different part of the wave, looking at a choice that no longer fits. The feeling was real. The timing was the problem. Your clearest self shows up once the wave has moved through, after the high or the low has passed.\n\nHow often have you reacted in a big moment, then wished you'd waited a day? That regret is the wave catching you before it passed.\n\nThe waves may run bigger in perimenopause and menopause. Because estrogen and progesterone help steady your moods, and both are fluctuating, your emotional swings can get sharper and harder to ride for a while, so a feeling that once moved through in an hour can now flood you and take longer to clear. You may notice it as crying more easily, a shorter fuse, or moods that feel more extreme than the situation calls for.\n\nAt your best, you let the wave move before you act on it. You feel the feeling fully, and you wait for the peak to pass before you make the call. When you do, you make far fewer choices you have to walk back, and you stop handing your hardest feelings to the people who didn't earn them.",
    "suggestions": "Start noticing where you are in a wave before you act, especially on anything that matters. When a strong feeling hits, let it be there, but put a gap between the feeling and the action. \"I'll respond tomorrow\" protects you from the choices made at the peak. You don't need to suppress what you feel, you need to time your actions for after the wave moves through.",
    "actionRewrite": "Your feelings move in waves, and acting at the peak is where you get into trouble, so a small gap between feeling and action protects you. Let the strongest part pass and you make far fewer choices you wish you could take back. A couple of things to try:\n- This week, when a strong feeling hits, put a gap between the feeling and the action. On anything that matters, wait until tomorrow before you send, commit, or decide.\n- You don't have to hide what you feel. Just let the strongest part pass before you act on it."
  },
  "Steady One": {
    "archetype": "Steady One",
    "title": "The Steady One",
    "tagline": "Your emotions run fairly even. The cost is missing what you feel until it piles up.",
    "body": "You don't swing much. Where others ride big highs and lows, you stay fairly level, and you can keep your head when feelings are running hot around you. This is a real strength. People lean on you for it, and you're often the calm one in the room.\n\nThe trouble is the hidden downside. Because you don't feel things in big waves, you can lose track of what you feel, brushing past it, staying busy, telling yourself you're fine. And feelings you never registered don't disappear. They can collect in the background until they spill over in a way that surprises even you, or settle in as a low, flat heaviness you can't quite explain.\n\nHere's how you know: you may go along fine for weeks, then hit a moment where it all lands at once and you wonder where it came from. It came from everything you walked past without noticing.\n\nThis is harder to manage in perimenopause and menopause. Because the hormones that used to keep you on an even keel are shifting, they can unsettle even someone as steady as you, and feelings you'd normally glide past can land with unexpected force. You may notice it as sudden tears that seem to come from nowhere, or a heaviness that's been building under the steadiness.\n\nAt your best, you check in on purpose, because your feelings won't always announce themselves. When you catch what you feel early, it stops ambushing you later, and that low, flat heaviness has less chance to build.",
    "suggestions": "Build in small check-ins, since your emotions won't grab you by the collar the way they do for other people. Once a day, ask yourself plainly: what am I feeling right now? Name it, even just to yourself. This is about catching what's accumulating before it spills. Your steadiness is a gift, and it can hide the cost until it's large. A few seconds of checking in is what keeps it from getting there.",
    "actionRewrite": "You stay level, which is a real strength, but it can hide what you're feeling until it piles up and spills over. A few seconds of checking in keeps small things from becoming a surprise flood. A couple of things to try:\n- Once a day this week, stop and ask yourself plainly: what am I feeling right now? Name it, even just to yourself.\n- Treat that check-in as catching what's building, before it lands all at once later."
  },
  "Holder": {
    "archetype": "Holder",
    "title": "The Holder",
    "tagline": "You hold your feelings down to keep going. You pay for it later, all at once.",
    "body": "When a feeling hits during the workday, you set it aside and carry on. You're good at it. You can hold it together through the meeting, the call, the hard conversation, and no one would know. This is a real skill, and there are moments it serves you well.\n\nThe trouble is that held feelings don't vanish, they wait. You push it down to get through the day, and then it may surface later, at home, at night, all at once, often bigger than if you'd felt it in the moment. The holding has a cost, and you pay it after hours, when you finally stop and everything you pressed down comes due.\n\nHere's the giveaway: you make it through the hard day composed and capable, then fall apart in the car, or snap at someone you love, or lie awake while everything you didn't feel during the day finally arrives. That's the bill for all the holding.\n\nThat bill is steeper in perimenopause and menopause. Because estrogen and progesterone help you contain and process emotion, and both are dropping, what you hold down can build faster and hit harder when it finally lands. You may notice it as evening crashes, a shorter fuse at home, or feeling fine all day and wrecked the moment you stop.\n\nAt your best, you let yourself feel a little of it in the moment, instead of holding it all for later. When you give the feeling a small outlet as you go, the evening stops being the place it all comes due, and you have more of yourself left for the people at home.",
    "suggestions": "Notice how much you hold during the day, and where it goes when you finally stop. You don't need to fall apart in meetings. You need small outlets during the day: a real exhale between calls, two minutes alone after something hard, naming the feeling to yourself instead of slamming the lid. Giving the feeling somewhere to go as you move through the day keeps the evening bill from becoming a flood.",
    "actionRewrite": "You hold your feelings down to get through the day, then pay for it later, all at once. When you let yourself feel a little of it in the moment, instead of saving all of it for after work, the evening stops being where everything lands, and you crash less at night. A couple of things to try:\n- This week, give a hard feeling a small outlet during the day: a slow exhale between calls, two minutes alone after a tough moment, or naming the feeling to yourself instead of pushing it down.\n- Notice where those pushed-down feelings tend to go when you finally stop at night, and try letting yourself feel a bit more of them during the day, so less of it is waiting for you at home."
  },
  "Sponge": {
    "archetype": "Sponge",
    "title": "The Sponge",
    "tagline": "You absorb other people's stress as if it's your own. Most of what you carry was never yours.",
    "body": "You feel what's around you. Walk into a tense room and you can pick it up. Sit near someone anxious and their stress can become yours within minutes. This comes from real sensitivity and real care, you're tuned to other people. But it means you may spend your day carrying stress that didn't start with you.\n\nThe trouble may be that you rarely notice the handoff. Someone offloads their panic, their deadline, their bad mood, and you may absorb it without realizing it was ever theirs, then carry it for hours as if it were yours to solve, when a chunk of what's weighing on you walked in on someone else.\n\nHere's how you know: you can end a day wrung out and anxious, and when you trace it back, the heaviest things weren't even your problems, they were the ones you absorbed from the people around you.\n\nThat absorbed stress weighs more now, too. Estrogen and progesterone are part of what keeps your nervous system calm, and as they drop, stress can land harder and take longer to clear. So everyday stress, including the stress you pick up from others, can feel louder and take longer to shake. You may notice it as feeling drained after time with certain people, or carrying a tension you can't trace to anything of your own.\n\nAt your best, you learn to tell the difference between your stress and theirs. When you stop carrying what was never yours, you end the day far less wrung out, with energy that's your own.",
    "suggestions": "Start asking one question when you feel stress climbing: is this mine? Naming \"this is hers, not mine\" is often enough to set it down. You can't always avoid stressful people, especially at work, but you can stop automatically absorbing and solving their stress as if it's your job. Notice who you leave drained, and give yourself a small reset after them, a breath, a short walk, a moment alone.",
    "actionRewrite": "You absorb other people's stress as if it's your own, so much of what you carry was never yours to hold. Learning to tell yours from theirs means you put a lot of it down and end the day less wrung out. A couple of things to try:\n- This week, when you feel stress climbing, ask one question: is this mine? Naming \"this is theirs, not mine\" is often enough to set it down.\n- Notice which people leave you most drained, and give yourself a small reset after them where you can: a breath, a short walk, a moment alone."
  },
  "Rusher": {
    "archetype": "Rusher",
    "title": "The Rusher",
    "tagline": "Under stress, you speed up and treat everything as urgent. The urgency itself is what burns you out.",
    "body": "When stress hits, you go faster. You move quickly, get things done, clear the pressure by attacking it head-on. In real emergencies this serves you, you're the one who acts while others freeze. But your system may treat almost everything as urgent, and most of it isn't.\n\nThe trouble is the manufactured urgency. You rush to be free of the pressure, but the moment one thing is done, another takes its place, and the rushing never ends because the finish line keeps moving. You may hurry through things that didn't need hurrying, you struggle to relax because there's always something pulling at you, and the constant speed wears you down. Underneath the productivity, it's a body running at full speed all day with no off switch.\n\nHere's the tell: you tell yourself you'll relax once you're caught up, but you're never caught up, because the urgency isn't about the work, it's the setting your stress runs at.\n\nThe constant rushing wears you down faster now. Because you have less of the hormonal buffer that used to absorb pressure, running your stress response at full speed all day pushes you toward burnout faster, and recovery can take longer. You may notice it as a wired, can't-switch-off feeling, trouble winding down at night, or exhaustion that rest doesn't fix.\n\nAt your best, you let pressure exist without acting on all of it at once. You get wise about what needs hurrying and what only feels like it does, and let the rest move at its real pace. When you do, the wired feeling eases, you can finally wind down at night, and you wake with more to give.",
    "suggestions": "Start questioning the urgency before you act on it: does this need to happen right now, or does it just feel that way? Most of what feels urgent can wait an hour without consequence. Practice letting one thing sit instead of rushing it, and notice that the sky doesn't fall. You can't always slow the pace around you, but you can stop adding speed that isn't required.",
    "actionRewrite": "Under stress you speed up and treat everything as urgent, and the constant rushing wears you down, more than the work ever does. When you let the things that can wait sit for a bit, you stop running at full speed all day and finally wind down at night. A couple of things to try:\n- This week, before you rush something, ask: does this need to happen right now, or does it just feel that way? Most of it can wait an hour.\n- Practice letting one thing sit instead of hurrying it, and notice that nothing falls apart."
  },
  "Freezer": {
    "archetype": "Freezer",
    "title": "The Freezer",
    "tagline": "Under stress, you go still and quiet, and it settles into your body. You shut down rather than speed up.",
    "body": "When stress hits, you don't rush, you freeze. You go quiet, pull inward, and the pressure settles into your body while everything seems to slow and lock up. This is a real nervous-system response. Where others speed up, your system braces and holds still.\n\nThe trouble is that the stress doesn't leave, it lodges. Because you go still instead of letting it out, the pressure can stay in your body, a tight chest, a clenched jaw, a held breath, and it builds while you carry on looking calm on the outside, even as the stress accumulates with nowhere to go.\n\nYou may seem composed under pressure while your body tells a different story, tension you only notice later, a stiffness or exhaustion that shows up after the stressful thing has passed.\n\nThe frozen stress holds on longer now than it once did. Because shifting estrogen and progesterone leave your nervous system more reactive and slower to come back down, the stress that locks into your body can hold longer and be harder to release than it did. You may notice it as physical tension that lingers, trouble settling even when the pressure's gone, or a wiped-out feeling after you finally unfreeze.\n\nAt your best, you find ways to unlock the freeze and move the stress through, instead of letting it set into your body and stay. When you do, it stops settling into your shoulders and your chest for hours, and you come back to yourself faster.",
    "suggestions": "Notice when you've gone still and braced, the held breath, the locked shoulders, that's your freeze, and naming it starts to thaw it. The stress needs a way out of your body, so when you can, move it: stand up, shake out your hands, take a few slow breaths, step outside. Even small movement signals your system that the threat has passed. You can't always avoid what triggers the freeze, but you can help your body come out of it instead of staying locked.",
    "actionRewrite": "Under stress you go still and quiet, and it lodges in your body, so the stress needs a way out rather than a place to sit. Moving it through means it doesn't set into tense shoulders and a tight chest that linger for hours. A couple of things to try:\n- When you notice you've gone still and braced, the held breath, the tight shoulders, name it. That alone starts to loosen the freeze.\n- Then move it out: stand up, shake out your hands, take a few slow breaths, or step outside. Small movement tells your body the pressure has passed."
  }
};
